#!/usr/bin/env bash
# Gives information about the school file.
file=school
if test -e "$file"; then
	echo "$file school file exists"
	if [ -s "$file" ]; then
		echo "$file school file is not empty"
	else
		echo "$file school file is empty"
	fi
	if test -f "$file"; then
		echo "$file school is a regular file"
	fi
else
	echo "$file school file does not exist"
fi
